// NOTE: Assertions have been autogenerated by utils/update_mc_test_checks.py UTC_ARGS: --version 6
// RUN: llvm-mc -triple=amdgpu9.50 -show-encoding %s | FileCheck --check-prefix=GFX950 %s
// RUN: llvm-mc -triple=amdgpu9.42 -show-encoding %s | FileCheck --check-prefix=GFX942 %s

v_pk_add_f32 v[4:5], v[0:1], v[2:3] op_sel:[0,1] op_sel_hi:[1,1]
// GFX942: v_pk_add_f32 v[4:5], v[0:1], v[2:3] op_sel:[0,1] ; encoding: [0x04,0x50,0xb2,0xd3,0x00,0x05,0x02,0x18]
// GFX950: v_pk_add_f32 v[4:5], v[0:1], v[2:3] op_sel:[0,1] ; encoding: [0x04,0x48,0xb2,0xd3,0x02,0x01,0x02,0x18]

v_pk_mul_f32 v[4:5], v[0:1], v[2:3] op_sel:[0,1] op_sel_hi:[1,1]
// GFX942: v_pk_mul_f32 v[4:5], v[0:1], v[2:3] op_sel:[0,1] ; encoding: [0x04,0x50,0xb1,0xd3,0x00,0x05,0x02,0x18]
// GFX950: v_pk_mul_f32 v[4:5], v[0:1], v[2:3] op_sel:[0,1] ; encoding: [0x04,0x48,0xb1,0xd3,0x02,0x01,0x02,0x18]

v_pk_fma_f32 v[6:7], v[0:1], v[2:3], v[4:5] op_sel:[0,1,1] op_sel_hi:[1,1,1]
// GFX942: v_pk_fma_f32 v[6:7], v[0:1], v[2:3], v[4:5] op_sel:[0,1,1] ; encoding: [0x06,0x70,0xb0,0xd3,0x00,0x05,0x12,0x1c]
// GFX950: v_pk_fma_f32 v[6:7], v[0:1], v[2:3], v[4:5] op_sel:[0,1,1] ; encoding: [0x06,0x68,0xb0,0xd3,0x02,0x01,0x12,0x1c]

v_pk_add_f32 v[4:5], v[0:1], v[2:3] op_sel:[1,1] op_sel_hi:[1,1]
// GFX942: v_pk_add_f32 v[4:5], v[0:1], v[2:3] op_sel:[1,1] ; encoding: [0x04,0x58,0xb2,0xd3,0x00,0x05,0x02,0x18]
// GFX950: v_pk_add_f32 v[4:5], v[0:1], v[2:3] op_sel:[1,1] ; encoding: [0x04,0x58,0xb2,0xd3,0x00,0x05,0x02,0x18]

v_pk_add_f32 v[4:5], v[0:1], v[2:3] op_sel:[1,0] op_sel_hi:[1,1]
// GFX942: v_pk_add_f32 v[4:5], v[0:1], v[2:3] op_sel:[1,0] ; encoding: [0x04,0x48,0xb2,0xd3,0x00,0x05,0x02,0x18]
// GFX950: v_pk_add_f32 v[4:5], v[0:1], v[2:3] op_sel:[1,0] ; encoding: [0x04,0x48,0xb2,0xd3,0x00,0x05,0x02,0x18]

v_pk_add_f32 v[4:5], v[0:1], v[2:3] op_sel:[0,0] op_sel_hi:[1,1]
// GFX942: v_pk_add_f32 v[4:5], v[0:1], v[2:3]     ; encoding: [0x04,0x40,0xb2,0xd3,0x00,0x05,0x02,0x18]
// GFX950: v_pk_add_f32 v[4:5], v[0:1], v[2:3]     ; encoding: [0x04,0x40,0xb2,0xd3,0x00,0x05,0x02,0x18]
